# File managed by pluginsync
sudo: false
language: go
go:
- 1.6.3
- 1.7.1
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.3
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: Cf2BuX7/kSFlGsTrYTHmeJ/7c4aRcOxulhTEoD1C7GVYMdlSeK1Jvnklef5Dzs/l223mNuhm6oR4pA27mSOFOgWtBj/5+g1vHBcPdQd3rEg6mIxb0ec9BZQMZwCgl3/8wasKmQuobwBT/bsEB9zuV84Gqdc78FrAX7Lw9QPx9PazMqOUQaI7frMoP87Ln72WuVhbc34BSBf/PTKKI2eWM/XGRKi5m2Zyp33rN1cB6/tM7kxPp51brODvCTyhIYZSLZt3ywdyJ5kcYGm7o5hFpKTg9nm0UHkeQC7dEgjL4DIE5sPGVxJL8od0ptr7GncJahKO2EsuiVd6nC7ulOdAdHOgFshIgZzvr8UUZVyOSQX0Vf1amGuNPj4qjdUGKvCLNL3dbIFzyF/67CNlIDPTziSQbk5BrS50qbvfb4fifhPl1MGg9e9O11aPBCqxg70lCPIxIwedCbDshoPvQQMtKjnfX7yj8iQlnwFcLQsLeFkpPOGxq4d5CXwkp9TDWcaKf8WhOEu8qDA5Bttf0Zh7CcdmYXQSDaSpfWh955x+wg3j+lyvqFKwwKkiN3PX/1bdhNtVoTQ5Hc1Ib9J+jcLXF6fSwzyjhU+BpdQSoqveZCLIYD9rrpDzFygnX5NPSwb3jA47jVwh6LFPlUodzP8fMka5EXfJ+/TGLGjcgaiADfo=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-pcm
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: Cf2BuX7/kSFlGsTrYTHmeJ/7c4aRcOxulhTEoD1C7GVYMdlSeK1Jvnklef5Dzs/l223mNuhm6oR4pA27mSOFOgWtBj/5+g1vHBcPdQd3rEg6mIxb0ec9BZQMZwCgl3/8wasKmQuobwBT/bsEB9zuV84Gqdc78FrAX7Lw9QPx9PazMqOUQaI7frMoP87Ln72WuVhbc34BSBf/PTKKI2eWM/XGRKi5m2Zyp33rN1cB6/tM7kxPp51brODvCTyhIYZSLZt3ywdyJ5kcYGm7o5hFpKTg9nm0UHkeQC7dEgjL4DIE5sPGVxJL8od0ptr7GncJahKO2EsuiVd6nC7ulOdAdHOgFshIgZzvr8UUZVyOSQX0Vf1amGuNPj4qjdUGKvCLNL3dbIFzyF/67CNlIDPTziSQbk5BrS50qbvfb4fifhPl1MGg9e9O11aPBCqxg70lCPIxIwedCbDshoPvQQMtKjnfX7yj8iQlnwFcLQsLeFkpPOGxq4d5CXwkp9TDWcaKf8WhOEu8qDA5Bttf0Zh7CcdmYXQSDaSpfWh955x+wg3j+lyvqFKwwKkiN3PX/1bdhNtVoTQ5Hc1Ib9J+jcLXF6fSwzyjhU+BpdQSoqveZCLIYD9rrpDzFygnX5NPSwb3jA47jVwh6LFPlUodzP8fMka5EXfJ+/TGLGjcgaiADfo=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-pcm
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
- provider: releases
  api_key:
    secure: h6iu131+0Dtr+fS3f++DnL5KegS1O8tdnPFt9EQuJbRRp8U2DaF8unyIQ7OVxOl3W/d6W88KZTnTOK3gUX6gTW4eXYjVQhjzkiB9FWvsyHOxwKkxNLo6OIq5XU9uZHhbVsRUUubo0I2ly4pzvnTcv2FigEV2uUKRqT87kpFMEBDAsiPNvfk75KBNjLQ3vPuyq7Czu1SUX3iYbCP14Rlp5nTjbhl8epLy7hngnysxzeDFrYhN6bMY+6XD0vUoAKooZgZ8Avm+KlciSEs+jOxEQCNrKQFIyCez+c/S8/X7nOFmaswbuhJEiIlVWCH0pkHRC1thjXPywITtVdlG5Ehor5kQgA8N1h+V4c9GjyJWyml2Sj9RxmsrcFO9FVuT+c46ZeF7qO4I6++5kO9xNONXD18R1LfTmXPtdUXJHxul6g6gxjY/HJ2+Z5sixMCVJWoeAebssHEntjJfxC3OqLNG2nAg61Og8RDsecdJ9xH8jgn6v6SKoRdxMTY8FtY8am5HnvHOLPa/w2HwreBtfnQEMDfjvCgDbrxrXQ16+oF+zlqV182mwkpFML2/FpfXnRpgLo5BigzsiSEch950IvHznqbeGAh//a+gSQ95huxXeSbfouJdHsqfMTbBiH83UFhrdABfTXwKXYgNfU/idkykbVwJR4ELZzplKpHh1wBXkug=
  file:
    - release/snap-plugin-collector-pcm_linux_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-collector-pcm
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.1"
